//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::{
    ActiveModelBehavior, ColumnDef, ColumnTrait, ColumnType, ColumnTypeTrait, DeriveActiveModel,
    DeriveColumn, DeriveEntity, DeriveModel, DerivePrimaryKey, EntityName, EntityTrait, EnumIter,
    PrimaryKeyTrait, Related, RelationDef, RelationTrait,
};
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "book_files"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub category_id: i64,
    pub path: String,
    pub title: Option<String>,
    pub kind: String,
    pub size: i64,
    pub mtime: i64,
    pub page_count: i64,
    pub pages_json: Option<String>,
    pub content_signature: Option<String>,
    pub is_oversized: bool,
    pub avg_page_pixels: i64,
    pub is_favorite: bool,
    pub cover_path: Option<String>,
    pub created_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CategoryId,
    Path,
    Title,
    Kind,
    Size,
    Mtime,
    PageCount,
    PagesJson,
    ContentSignature,
    IsOversized,
    AvgPagePixels,
    IsFavorite,
    CoverPath,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Categories,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::CategoryId => ColumnType::Integer.def(),
            Self::Path => ColumnType::Text.def().unique(),
            Self::Title => ColumnType::Text.def().null(),
            Self::Kind => ColumnType::Text.def(),
            Self::Size => ColumnType::Integer.def(),
            Self::Mtime => ColumnType::Integer.def(),
            Self::PageCount => ColumnType::Integer.def(),
            Self::PagesJson => ColumnType::Text.def().null(),
            Self::ContentSignature => ColumnType::Text.def().null(),
            Self::IsOversized => ColumnType::Boolean.def(),
            Self::AvgPagePixels => ColumnType::Integer.def(),
            Self::IsFavorite => ColumnType::Boolean.def(),
            Self::CoverPath => ColumnType::Text.def().null(),
            Self::CreatedAt => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Categories => Entity::belongs_to(super::categories::Entity)
                .from(Column::CategoryId)
                .to(super::categories::Column::Id)
                .into(),
        }
    }
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
