//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::{
    ActiveModelBehavior, ColumnDef, ColumnTrait, ColumnType, ColumnTypeTrait, DeriveActiveModel,
    DeriveColumn, DeriveEntity, DeriveModel, DerivePrimaryKey, EntityName, EntityTrait, EnumIter,
    PrimaryKeyTrait, Related, RelationDef, RelationTrait,
};
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "categories"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub library_id: i64,
    pub parent_id: Option<i64>,
    pub name: String,
    pub path: String,
    pub mtime: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    LibraryId,
    ParentId,
    Name,
    Path,
    Mtime,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    BookFiles,
    SelfRef,
    Libraries,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::LibraryId => ColumnType::Integer.def(),
            Self::ParentId => ColumnType::Integer.def().null(),
            Self::Name => ColumnType::Text.def(),
            Self::Path => ColumnType::Text.def().unique(),
            Self::Mtime => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::BookFiles => Entity::has_many(super::book_files::Entity).into(),
            Self::SelfRef => Entity::belongs_to(Entity)
                .from(Column::ParentId)
                .to(Column::Id)
                .into(),
            Self::Libraries => Entity::belongs_to(super::libraries::Entity)
                .from(Column::LibraryId)
                .to(super::libraries::Column::Id)
                .into(),
        }
    }
}

impl Related<super::book_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookFiles.def()
    }
}

impl Related<super::libraries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Libraries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
